name: CI

on:
  push:
    branches:
      - develop
      - master
      - 'releases/**'
  pull_request:
    branches:
      - develop
      - master
      - 'releases/**'

jobs:
  run-tests:
    strategy:
      matrix:
        compatibility:
          - develop
          #- latest
        perl:
          - '5.38'
          - '5.34'
          - '5.26'
        runner:
          - ubuntu-22.04

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v2

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: Install Zonemaster-Engine with dependencies
        uses: ./.github/actions/install-with-dependencies
        with:
          zonemaster_ldns_branch: ${{ matrix.compatibility }}

      - name: Show content of log files
        if: ${{ failure() }}
        run: cat /home/runner/.cpanm/work/*/build.log

      - name: Test
        run: |
          prove -lv t
